version: '2'
services:
  postgres:
    build:
      context: ../
    ports:
     - "8432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - AWS_ACCESS_KEY_ID=AWSAccessKeyId
      - AWS_SECRET_ACCESS_KEY=AWSSecretKey
      - WALE_S3_PREFIX=s3://bucketdockerpostgreswale
      - WALE_S3_ENDPOINT=http+path://fakes3:4569
    depends_on:
     - fakes3
  fakes3:
    volumes:
     - .:/var/data/fake-s3
    image:  spurious_fakes3